import {
  addCircleOutline,
  alertCircleOutline,
  checkmarkCircleOutline,
  checkmarkOutline,
  clipboardOutline,
  closeOutline,
  createOutline,
  cubeOutline,
  enterOutline,
  exitOutline,
  homeOutline,
  logInOutline,
  powerOutline,
  searchOutline,
  timeOutline,
  trashOutline,
  trendingDownOutline,
  trendingUpOutline,
} from 'ionicons/icons';

/** Registro explícito dos ícones usados (tree-shaking: só estes entram no bundle). */
export const APP_ICONS = {
  'add-circle-outline': addCircleOutline,
  'alert-circle-outline': alertCircleOutline,
  'checkmark-circle-outline': checkmarkCircleOutline,
  'checkmark-outline': checkmarkOutline,
  'clipboard-outline': clipboardOutline,
  'close-outline': closeOutline,
  'create-outline': createOutline,
  'cube-outline': cubeOutline,
  'enter-outline': enterOutline,
  'exit-outline': exitOutline,
  'home-outline': homeOutline,
  'log-in-outline': logInOutline,
  'power-outline': powerOutline,
  'search-outline': searchOutline,
  'time-outline': timeOutline,
  'trash-outline': trashOutline,
  'trending-down-outline': trendingDownOutline,
  'trending-up-outline': trendingUpOutline,
};
